# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 10:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20171122_1610'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': 'MySubscriber', 'verbose_name_plural': 'MySubscribers'},
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='name',
        ),
    ]
