# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='new_product',
            field=models.BooleanField(default=True),
        ),
    ]
